plugins: [
    "quark_plugin_hamiltonian_simulation",
    ]

pipeline: 
    - "free_fermion_benchmark": {lx: 2, ly: 4, periodic: true, n_trot: 5, two_spin_species: true, create_plot: true}
    - "output_qiskit"
    - "aer_simulator"
