[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# can be empty if no extra settings are needed, presence enables setuptools-scm

[project.urls]
Homepage = "https://github.com/egranet/QUARK-plugin-hamiltonian-simulation"

[project]
name = "QUARK-plugin-hamiltonian-simulation"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
dependencies = ["quark-framework>=0.4.4",
"scipy>=1.16.3",
"qiskit==2.0.3",
"qiskit_aer>=0.15.1",
"matplotlib>=3.9.3"]
