[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
# can be empty if no extra settings are needed, presence enables setuptools-scm

[project.urls]
Homepage = "https://github.com/egranet/QUARK-plugin-hamiltonian-simulation"

[project]
name = "QUARK-plugin-hamiltonian-simulation"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
dependencies = [
    "quark-framework>=0.4.4",
    "quark-plugin-quantinuum>=0.0.1",
    "scipy>=1.16.3",
    "qiskit>=2.0.3",
    "matplotlib>=3.9.3",
    "pytket-qiskit>=0.77.0",
    "numpy>=2.3.5",
]
[dependency-groups]
dev = [
    "pytest (>=8.0.0,<9.0.0)",
    "ruff (>=0.12.0,<0.13.0)",
    "mypy >=1.9.0,<2",
    "scipy-stubs>=1.16.2.0",
]
