plugins: [
    "quark_plugin_hamiltonian_simulation",
    "quark_plugin_quantinuum"
    ]

pipeline: 
    - "free_fermion_benchmark": {lx: 4, ly: 4, periodic: false, n_trot: 3, two_spin_species: false}
    # - "output_qiskit"
    # - "aer_simulator"
